# Site settings
title: Atomic Design by Brad Frost
email: brad@bradfrost.com
description: > # this means to ignore newlines until "baseurl:"
  Learn how to create and maintain digital design systems, allowing your team to roll out higher quality, more consistent UIs faster than ever before.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bradfrost.com" # the base hostname & protocol for your site
twitter_username: brad_frost
github_username: bradfrost
product_link: http://shop.bradfrost.com

# Build settings
markdown: kramdown
exclude:
  [
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "package-lock.json",
    "_sass",
    ".sass-cache",
    ".DS_Store",
    "js/src",
  ]
port: 4200

# Sass configuration
sass:
  load_paths:
    - node_modules
